// ----------------------------------------------------------------------------
// 初期ドメイン案の生成
//
// Phase 5 ではヒューリスティックでまず叩き台を出す:
//   1. プレフィックス / suffix の正規表現で「同種命名」をクラスタリング
//   2. パッケージディレクトリで分離されているものは独立ドメイン
//   3. それ以外は "unclassified"
//
// 将来的に LLM 補完を入れる際は、本関数の戻り値を seed として LLM パスへ渡す
// 設計にしてある。LLM 統合は src/domains/suggest-llm.ts に分離予定。
// ----------------------------------------------------------------------------

import type { ComponentType } from "../html/sections.js";
import type { KnowledgeGraph } from "../types/graph.js";
import type { DomainDef, DomainMemberRef, DomainsConfig } from "./types.js";

const PREFIX_RE = /^([A-Z][A-Za-z]+?)(?=[A-Z_]|$)/;
const MIN_CLUSTER_SIZE = 2;

interface NamedItem {
  readonly type: ComponentType;
  readonly name: string;
}

export function suggestInitialDomains(graph: KnowledgeGraph): DomainsConfig {
  const items: NamedItem[] = [
    ...graph.apexClasses
      .filter((c) => !c.isTest)
      .map((c) => ({ type: "apex" as const, name: c.fullyQualifiedName })),
    ...graph.apexTriggers.map((t) => ({ type: "trigger" as const, name: t.fullyQualifiedName })),
    ...graph.lwcs.map((l) => ({ type: "lwc" as const, name: l.fullyQualifiedName })),
    ...graph.objects.map((o) => ({ type: "object" as const, name: o.fullyQualifiedName })),
    ...graph.flows.map((f) => ({ type: "flow" as const, name: f.fullyQualifiedName })),
  ];

  const byPrefix = new Map<string, NamedItem[]>();
  const others: NamedItem[] = [];
  for (const it of items) {
    const prefix = extractPrefix(it.name);
    if (prefix === null) {
      others.push(it);
      continue;
    }
    const list = byPrefix.get(prefix) ?? [];
    list.push(it);
    byPrefix.set(prefix, list);
  }

  const domains: DomainDef[] = [];
  for (const [prefix, members] of byPrefix) {
    if (members.length < MIN_CLUSTER_SIZE) {
      others.push(...members);
      continue;
    }
    domains.push({
      id: toId(prefix),
      label: prefix,
      description: `auto-suggested by prefix "${prefix}" (Phase 5 heuristic; please refine)`,
      members: members.map<DomainMemberRef>((m) => ({ type: m.type, name: m.name })),
    });
  }

  if (others.length > 0) {
    domains.push({
      id: "unclassified",
      label: "Unclassified",
      description:
        "Components that did not fit a heuristic prefix cluster. Move them to the right domain manually.",
      members: others.map<DomainMemberRef>((m) => ({ type: m.type, name: m.name })),
    });
  }

  domains.sort((a, b) => {
    if (a.id === "unclassified") return 1;
    if (b.id === "unclassified") return -1;
    return a.id.localeCompare(b.id);
  });

  return {
    version: 1,
    domains,
    notes:
      "Auto-generated by `yohaku domains init`. Refine labels, descriptions, and group splits, then commit to source control. Subsequent builds will treat this file as the source of truth.",
  };
}

function extractPrefix(name: string): string | null {
  // 末尾の "Test" を取り除く
  const stripped = name.replace(/Test$/, "");
  // dot を含む (Account.Industry__c 等の Field) — オブジェクト名を prefix とする
  const dotIdx = stripped.indexOf(".");
  if (dotIdx > 0) return stripped.slice(0, dotIdx);
  const m = stripped.match(PREFIX_RE);
  if (m === null) return null;
  return m[1] ?? null;
}

function toId(prefix: string): string {
  return prefix
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-");
}
